---
title: "pres_data"
output: html_document
---

### Modélisation de l'épaisseur des glaciers

Pour estimer le volume annuel et la contribution hydrique de chaque glacier, des modélisations de l'évolution de l'épaisseur des glaciers entre 2020 et 2050 ont été utilisées. Ces modélisations sont issues d'un travail de recherche conduit par un ensemble de chercheurs de l’Université de Lausanne en Suisse (UNIL, Samuel Cook et Guillaume Jouvet), de l'Université Grenoble Alpes en France (UGA, Antoine Rabatel et Romain Millan), de l'Université de Zurich en Suisse (Inès Dussaillant) et de l'Université de Bruxelles en Belgique (Harry Zekollary). Leur approche repose sur une méthode d'intelligence artificielle basé sur l'apprentissage profond, capable d'estimer l'évolution future des glaciers à partir de données issues de la télédétection satellitaire et d'un modèle dynamique. Les résultats de leur travail couvrent l'ensemble de l'arc alpin européen. Pour plus de détails, voir l'article ([lien](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023GL105029)).\
<br>
L'apprentissage du modèle repose également sur l'analyse historique des changements glaciaires de 2000 et 2019, garantissant ainsi que les modélisations reflètent l'évolution observée des glaciers au cours des 20 dernières années.\
Les sorties du modèle ont été traitées afin de corriger certains pixels ayant des valeurs aberrantes. Cela permet de limiter la surestimation du stock de glace pour les glaciers impactés par les pixels aberrants.
<br>
A partir des estimations de l'épaisseur de glace, il est donc possible de connaître le volume de glace compris dans la surface d'un glacier. En sommant la valeur d'épaisseur de glace de chacun des pixels compris dans l'emprise d'un glacier, on obtient le volume total du glacier pour une année donnée. Par ailleurs, la contribution hydrique annuelle d'un glacier a aussi été calculée. Elle correspond à l'évolution du volume du glacier d'une année à l'autre. Elle est convertie en une contribution annuelle moyenne dont la valeur numérique est donnée en litres par seconde (l/s). A noter que si, pour une année donnée, un glacier gagne du volume, sa contribution moyenne annuelle est alors négative, c'est-à-dire que pour cette année là, le glacier aura à l'échelle de l'année, davantage stocké de la masse qu'il n'en aura perdu.
  
