---
title: "pres_data"
output: html_document
---


### Trajectoires d'évolution

Le travail de modélisation réalisé par S. Cook et al. (2023) propose trois trajectoires d'évolution des glaciers basées sur ce que l'on appelle la "perte engagée" des glaciers. Celle-ci correspond au niveau minimum que les glaciers sont amenés à perdre dans les prochaines décennies compte-tenu de leur temps de réponse (leur inertie) à un changement des conditions environnementales. Ce temps de réponse est lié à la dynamique d'écoulement du glacier et est propre à chaque glacier en fonction de ses caractéristiques morpho-topographiques. Ainsi, ces trois trajectoires de "perte engagée" ont été établies à partir de différentes périodes historiques d'observations.\
<br>

#### Trois trajectoires prospectives (2020-2050)

<div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;">

<div style="padding: 15px;">
<h4>Trajectoire optimiste</h4>
<p><strong>Hypothèse :</strong> Stabilisation des conditions de perte de volume glaciaire à celles de la période 2000-2019</p>
<p><strong>Impact :</strong> Perte de 34 % du volume glaciaire à l’échelle de l’arc alpin</p>
</div>

<div style="padding: 15px;">
<h4>Trajectoire intermédiaire</h4>
<p><strong>Hypothèse :</strong> Extrapolation temporelle du taux de perte de masse de la période 2000-2022</p>
<p><strong>Impact :</strong> Perte de 46 % du volume glaciaire à l’échelle de l’arc alpin</p>
</div>

<div style="padding: 15px;">
<h4>Trajectoire pessimiste</h4>
<p><strong>Hypothèse :</strong> Poursuite de l’accélération récente de la perte via une extrapolation temporelle du taux de perte de masse de la période 2010-2022</p>
<p><strong>Impact :</strong> Perte de 65 % du volume glaciaire à l’échelle de l’arc alpin</p>
</div>

</div>  
  
<br>

### Contour des glaciers

Pour déterminer le contour des glaciers, le modèle utilise des données 2003 provenant de l'inventaire mondial des glaciers mis à disposition dans le cadre du [RGI Version 6](https://nsidc.org/data/nsidc-0770/versions/6).\
Afin d'assurer une cohérence spatiale entre les modélisations et la méthode d'extraction des données dans le cadre de ce projet, c'est ce même contour des glaciers qui a été adopté.\
<br>


<br>
